### ISSUE TITLE
Please publish new version to npmjs

### ISSUE THREAD

**Issue by fstoerkle** [munkychop/angular-utf8-base64#1]
Hey,

it would be cool if you could update this repo and npm publish the latest version of the original `angular-utf8-base64` (currently 0.0.5, see https://github.com/stranger82/angular-utf8-base64/blob/master/package.json#L3).

We want to move from bower to npm, and would like to use the latest version of that module. Thanks!

**Comment by munkychop** [comment]
@fstoerkle yes, it is on my TODO list. I'll try to make some time for this during the week.

**Comment by fstoerkle** [comment]
Awesome, thanks @munkychop

**Comment by munkychop** [comment]
@fstoerkle I have now updated to [the latest version published by @stranger82](https://github.com/stranger82/angular-utf8-base64/releases/tag/v0.0.5) and published to npm 😄 

https://www.npmjs.com/package/angular-utf8-base64

Note that I have also bumped the version number in order to match @stranger82's release.
